### ISSUE TITLE
Error in $awaitComponentsUntil

### ISSUE THREAD

**Issue by Snowcat228** [aoijs/documentation#143]
### Code of Conduct

- [X] I have read and agree to the aoijs docs project's [Code of Conduct](https://github.com/aoijs/documentation/blob/v5.1.2/.github/docs/CODE_OF_CONDUCT.md)

### What function on akarui.leref.ga is affected?

[$awaitComponentsUntil](https://aoi.js.org/docs/functions/awaitcomponentsuntil) 
^ Hope it's right it's hard to edit on mobile..

### What parts of the function would you like to see updated?

![Screenshot_20220727-160326_Chrome](https://user-images.githubusercontent.com/90235545/181284226-830b20da-4e76-4c72-91ea-be2136ac7081.jpg)

`Response` should be changed to `Respond`
It's just a tiny mistake :D

### Additional information

~Snowcat

**Comment by Neodevils** [comment]
Thanks for reaching to us, @Snowcat228. 

I'll be working on it after the current pull request merged. 🙌🏻
