### ISSUE TITLE
Incorrect function usage of $setTimeout

### ISSUE THREAD

**Issue by Snowcat228** [aoijs/documentation#148]
### Code of Conduct

- [X] I have read and agree to the aoijs docs project's [Code of Conduct](https://github.com/aoijs/documentation/blob/v5.1.2/.github/docs/CODE_OF_CONDUCT.md)

### What function on akarui.leref.ga is affected?

https://aoi.js.org/docs/functions/settimeout/

### What parts of the function would you like to see updated?

Incorrect Function usage.

Original:
`$setTimeout[duration;timeout data;timeout heartbeat (optional)]`

Correct usage: `$setTimeout[name;duration;timeoutData;returnId?;pulse]`

~From dodoGames#7509 on Discord

**Comment by Neodevils** [comment]
I'll be updating it.

**Comment by Neodevils** [comment]
- [x] The function has been updated on #145 . Thank you for your help! 🙌

**Comment by Leref** [comment]
Resolved.
